import math

# Constants
GRAVITY = 0.5
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
TILE_SIZE = 16
ITEM_SIZE = 8
HOTBAR_SIZE = 10
INVENTORY_SIZE = 4 * HOTBAR_SIZE
CHUNK_SIZE = 64
RENDER_DISTANCE = 2
WORLD_HEIGHT = 4
WORLD_WIDTH = 8
PLAYER_WIDTH = 20
PLAYER_HEIGHT = 42
HOTBAR_X = 200
HOTBAR_Y = 100
DIAGONAL_GRADIENT = math.sqrt(2) / 2
GRADIENTS_2D = ((1, 0), (-1, 0), (0, 1), (0, -1), (DIAGONAL_GRADIENT, DIAGONAL_GRADIENT), (-DIAGONAL_GRADIENT, DIAGONAL_GRADIENT), (DIAGONAL_GRADIENT, -DIAGONAL_GRADIENT), (-DIAGONAL_GRADIENT, -DIAGONAL_GRADIENT))